### ISSUE TITLE
Status tiling

### ISSUE THREAD

**Issue by valhalla540** [parnic/MMM-MyQ#1]
Hi, this is the first time I've communicated in github. I just installed your MMM-MyQ module for MM. Got it working, wanting to see the status of a garage door. I have two doors and its provide the status for both, but they are in boxes on top of each other. Is there a way to have the boxes side by side? I'm not savvy enough to understand the full breadth of your code so hoping you could point me in the right direct. Thanks!

**Comment by parnic** [comment]
Thanks for pointing this out - I didn't properly handle multiple devices. I will try to get that fixed up.

**Comment by valhalla540** [comment]
You're awesome. Great work on the module BTW. It works perfectly as is, buttons and all, once I figured out I had a virtualgaragedoor ;-)

**Comment by valhalla540** [comment]
![image](https://user-images.githubusercontent.com/49652024/130618138-553bc202-11dd-4d12-8a71-0683ecdf6b0b.png)
In case you need to what I was talking about. This is using position bottom_right

**Comment by parnic** [comment]
Latest commit has a new config property, `columns`, that lets you specify how to handle multiple devices. Set `columns` to `2` and your buttons should be side-by-side. Let me know how that works!

On a side note, I don't know why your buttons are overlapping your weather widget like that. My buttons don't overlap the widget directly above it, so I suspect that's a problem with the weather module you're using (rather than a problem with MyQ, but if you discover differently, do let me know).

**Comment by valhalla540** [comment]
Thanks for such a quick turnaround. Unfortunately the buttons don't appear. I did "git pull" (I think that's right) I see the new property the MMM-MyQ.js. I had added it to my config.js "`columns: 2,`"and the buttons disappeared. I removed it from config and changed it in the MMM-MyQ.js to 2 and it still didn't appear, returned it to 1 and still not there. Did I do something wrong...totally possible. 

Regarding the overlap....I just zoomed out a bit and it lines up nice now. Before the update anyway :)

**Comment by valhalla540** [comment]
[25.08.2021 07:21.01.997] [ERROR] Failed to fetch git data for MMM-MyQ: Error: block timeout reached
is showing on start up. I had forgotten to run the npm install after replacing the module, but not sure what's wrong now. Will keep seeing if I did something wrong and let you know. Sorry for being a PIA

**Comment by parnic** [comment]
Looks like this is just bad timing. MyQ has updated their API and the library I'm using, https://github.com/thomasmunduchira/myq-api, hasn't updated to the new version yet. Here's the ticket for that: https://github.com/thomasmunduchira/myq-api/issues/34 :(

**Comment by valhalla540** [comment]
Ha thanks for checking and working on it. You really do rock. I'll keep an eye on it. Thanks again!

**Comment by parnic** [comment]
@valhalla540 I went ahead and converted to a different library since there has been no movement from `myq-api`. Try latest!

**Comment by valhalla540** [comment]
Finally got around to figuring out how to clean up and reinstall the MMM-MyQ...it works a charm...thank you! you're awesome
